// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKi9CgiH39UMjKDyhNDhsCOMUwzS5sxe8',
    appId: '1:365820651364:web:6e090104b81b6d193dbc71',
    messagingSenderId: '365820651364',
    projectId: 'minimal-3e30d',
    authDomain: 'minimal-3e30d.firebaseapp.com',
    storageBucket: 'minimal-3e30d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1CroGmq-s-gJDh1G0jZiKB9j_hEQha-I',
    appId: '1:365820651364:android:0680bb9609ff58db3dbc71',
    messagingSenderId: '365820651364',
    projectId: 'minimal-3e30d',
    storageBucket: 'minimal-3e30d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2f47qTO6FClfmluQtJmk15dON93W9GWU',
    appId: '1:365820651364:ios:c8a5ce4878a3afb73dbc71',
    messagingSenderId: '365820651364',
    projectId: 'minimal-3e30d',
    storageBucket: 'minimal-3e30d.appspot.com',
    iosBundleId: 'com.example.authenticationFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2f47qTO6FClfmluQtJmk15dON93W9GWU',
    appId: '1:365820651364:ios:c8a5ce4878a3afb73dbc71',
    messagingSenderId: '365820651364',
    projectId: 'minimal-3e30d',
    storageBucket: 'minimal-3e30d.appspot.com',
    iosBundleId: 'com.example.authenticationFlutter',
  );
}
